/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Michael V (https://sketchfab.com/bossdeff)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-computer-room-a149d5bfcef6496c9a0606b5ce5ebf27
Title: Sci-Fi Computer Room
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, Html, useTexture } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import * as THREE from "three";

import scifiComputerRoom from "../assets/public/sci-fi_computer_room.glb";
import sammyPhoto from "../assets/SammyW.png";
import sammy1Photo from "../assets/Sammy1.jpg";
import audio from "../utils/audioManager";

const ScifiRoom = ({
  onPosterClick,
  onMonitorClick,
  onKeyboardClick,
  showLoading,
  loadingText,
  hideCard,
  ...props
}) => {
  const { nodes, materials } = useGLTF(scifiComputerRoom);
  const scifiComputerRoomRef = useRef();
  const { scene } = useThree();
  const [hovered, setHovered] = useState(false);
  const [monitorHovered, setMonitorHovered] = useState(false);
  const [keyboardHovered, setKeyboardHovered] = useState(false);
  const [isMobile, setIsMobile] = useState(() => window.innerWidth < 768);
  const photoTexture = useTexture(sammyPhoto);

  useEffect(() => {
    const onResize = () => setIsMobile(window.innerWidth < 768);
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, []);

  useEffect(() => {
    // Pure black void — no color, no skybox
    scene.background = new THREE.Color("#000000");
    // No fog — total darkness around the model
    scene.fog = null;

    // Boost Emission material brightness
    if (materials.Emission) {
      materials.Emission.emissiveIntensity = 3;
      materials.Emission.toneMapped = false;
      materials.Emission.needsUpdate = true;
    }
    if (materials.Emission_Blue) {
      materials.Emission_Blue.emissiveIntensity = 7;
      materials.Emission_Blue.toneMapped = false;
      materials.Emission_Blue.needsUpdate = true;
    }
  }, [materials, scene]);

  // Apply photo texture to a cloned Posters material
  const postersMaterial = React.useMemo(() => {
    const mat = materials.Posters.clone();
    photoTexture.flipY = false;
    mat.map = photoTexture;
    mat.needsUpdate = true;
    return mat;
  }, [materials.Posters, photoTexture]);

  // Change cursor on hover
  useEffect(() => {
    document.body.style.cursor =
      hovered || monitorHovered || keyboardHovered ? "pointer" : "auto";
    return () => {
      document.body.style.cursor = "auto";
    };
  }, [hovered, monitorHovered, keyboardHovered]);

  // Compute geometry centers for hint positioning
  const getCenter = React.useCallback((geometry) => {
    if (!geometry.boundingBox) geometry.computeBoundingBox();
    const center = new THREE.Vector3();
    geometry.boundingBox.getCenter(center);
    return [center.x, center.y, center.z];
  }, []);

  const handleMeshClick = (meshName, materialName) => (e) => {
    e.stopPropagation();
    console.log(`Mesh clicked: ${meshName} | Material: ${materialName}`);
  };

  return (
    <group ref={scifiComputerRoomRef} {...props} dispose={null}>
      {/* Light blue point lights for Desk and Monitor areas */}
      {/* Identity Card inside the 3D scene */}
      {!hideCard && (
        <Html
          position={[-0.6, 0.3, isMobile ? 1.3 : 1.8]}
          rotation={[0, -1.0, 0]}
          distanceFactor={1.5}
          transform
          style={{ pointerEvents: "auto" }}
        >
          <div className="w-[300px] bg-gradient-to-br from-blue-900/40 via-blue-800/25 to-cyan-900/30 backdrop-blur-md border border-blue-400/20 rounded-2xl p-5 shadow-2xl shadow-blue-500/10">
            {/* Photo with top-left and bottom-right slanty */}
            <div className="w-full flex justify-center mb-4">
              <div
                className="w-28 h-28 overflow-hidden border-2 border-cyan-400/40 shadow-lg shadow-cyan-500/20"
                style={{
                  clipPath:
                    "polygon(15% 0%, 100% 0%, 100% 15%, 100% 85%, 85% 100%, 0% 100%, 0% 85%, 0% 15%)",
                }}
              >
                <img
                  src={sammy1Photo}
                  alt="Sammy"
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
            {/* Name */}
            <h1 className="text-xl font-extrabold text-white text-center tracking-wide mb-1">
              Sammy
            </h1>
            {/* Tagline */}
            <p className="text-cyan-300 text-xs text-center font-medium mb-3">
              I build immersive 3D web experiences that captivate &amp; convert.
            </p>
            {/* Tech Stack */}
            <div className="flex flex-wrap justify-center gap-1.5 mb-4">
              {["React", "Three.js", "Tailwind", "Node.js", "JS"].map(
                (tech) => (
                  <span
                    key={tech}
                    className="px-2 py-0.5 text-[10px] font-semibold rounded-full bg-blue-500/15 text-cyan-200 border border-cyan-500/20 tracking-wide"
                  >
                    {tech}
                  </span>
                ),
              )}
            </div>
            {/* CTA Button */}
            <a
              href="/contact"
              onClick={() => audio.playClickSound()}
              className="block w-full text-center py-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 text-white font-bold text-xs tracking-wide shadow-lg shadow-cyan-500/25 hover:from-cyan-400 hover:to-blue-500 hover:shadow-cyan-400/40 transition-all duration-300"
            >
              Let's Work Together →
            </a>
          </div>
        </Html>
      )}

      <pointLight
        color="#7ad0ff"
        intensity={6}
        distance={8}
        position={[0, 1.5, 0]}
      />
      <pointLight
        color="#7ad0ff"
        intensity={5}
        distance={6}
        position={[1, 2, -1]}
      />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.987}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Desk_1}
          onClick={handleMeshClick("Object_2", "Desk_1")}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={postersMaterial}
          onClick={(e) => {
            e.stopPropagation();
            audio.playClickSound();
            setHovered(false);
            console.log("Mesh clicked: Object_3 | Material: Posters");
            if (onPosterClick) onPosterClick();
          }}
          onPointerOver={(e) => {
            e.stopPropagation();
            setHovered(true);
          }}
          onPointerOut={() => setHovered(false)}
        >
          {hovered && (
            <Html
              center
              position={getCenter(nodes.Object_3.geometry)}
              distanceFactor={7}
              style={{ pointerEvents: "auto" }}
            >
              <div
                className="flex items-center gap-1 bg-black/80 text-white text-[3px] px-1.5 py-0.5 rounded whitespace-nowrap shadow cursor-pointer border border-cyan-500/30"
                onClick={(e) => {
                  e.stopPropagation();
                  audio.playClickSound();
                  setHovered(false);
                  if (onPosterClick) onPosterClick();
                }}
              >
                <span className="text-cyan-400 text-[3px]">ⓘ</span>
                <span className="tracking-wide">About me</span>
              </div>
            </Html>
          )}
        </mesh>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Keyboard}
          onClick={(e) => {
            e.stopPropagation();
            audio.playClickSound();
            setKeyboardHovered(false);
            console.log("Mesh clicked: Object_4 | Material: Keyboard");
            if (onKeyboardClick) onKeyboardClick();
          }}
          onPointerOver={(e) => {
            e.stopPropagation();
            setKeyboardHovered(true);
          }}
          onPointerOut={() => setKeyboardHovered(false)}
        >
          {keyboardHovered && (
            <Html
              center
              position={getCenter(nodes.Object_4.geometry)}
              distanceFactor={7}
              style={{ pointerEvents: "auto" }}
            >
              <div
                className="flex items-center gap-1 bg-black/80 text-white text-[3px] px-1.5 py-0.5 rounded whitespace-nowrap shadow cursor-pointer border border-cyan-500/30"
                onClick={(e) => {
                  e.stopPropagation();
                  audio.playClickSound();
                  setKeyboardHovered(false);
                  if (onKeyboardClick) onKeyboardClick();
                }}
              >
                <span className="text-cyan-400 text-[3px]">⌨</span>
                <span className="tracking-wide">My Skills</span>
              </div>
            </Html>
          )}
        </mesh>
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.speaker_2}
          onClick={handleMeshClick("Object_5", "speaker_2")}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.BG_Dark}
          onClick={handleMeshClick("Object_6", "BG_Dark")}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Carpet}
          onClick={handleMeshClick("Object_7", "Carpet")}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Emission}
          onClick={handleMeshClick("Object_8", "Emission")}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Emission_Blue}
          onClick={handleMeshClick("Object_9", "Emission_Blue")}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Foam_Acoustic}
          onClick={handleMeshClick("Object_10", "Foam_Acoustic_1")}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.Foam_Acoustic}
          onClick={handleMeshClick("Object_11", "Foam_Acoustic_2")}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.Trim_Sheet_Wall}
          onClick={handleMeshClick("Object_12", "Trim_Sheet_Wall")}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Monitor_Single}
          onClick={(e) => {
            e.stopPropagation();
            audio.playClickSound();
            setMonitorHovered(false);
            console.log("Mesh clicked: Object_13 | Material: Monitor_Single");
            if (onMonitorClick) onMonitorClick();
          }}
          onPointerOver={(e) => {
            e.stopPropagation();
            setMonitorHovered(true);
          }}
          onPointerOut={() => setMonitorHovered(false)}
        >
          {monitorHovered && (
            <Html
              center
              position={getCenter(nodes.Object_13.geometry)}
              distanceFactor={7}
              style={{ pointerEvents: "auto" }}
            >
              <div
                className="flex items-center gap-1 bg-black/80 text-white text-[3px] px-1.5 py-0.5 rounded whitespace-nowrap shadow cursor-pointer border border-cyan-500/30"
                onClick={(e) => {
                  e.stopPropagation();
                  audio.playClickSound();
                  setMonitorHovered(false);
                  if (onMonitorClick) onMonitorClick();
                }}
              >
                <span className="text-cyan-400 text-[3px]">⟐</span>
                <span className="tracking-wide">Projects</span>
              </div>
            </Html>
          )}
        </mesh>
      </group>
    </group>
  );
};

export default ScifiRoom;
